version: "3"

services:
  spring-app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env

  frontend:
    image: nginx:alpine
    volumes:
      - ./src/main/resources/static:/usr/share/nginx/html
    ports:
      - "80:80"




