version: "3"

services:
  postgres-db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=api_player
      - POSTGRES_USER=user123
      - POSTGRES_PASSWORD=user123
    volumes:
      - postgres-data:/var/lib/postgresql/data

  spring-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ep-summer-hat-a4zj79yc-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require
      - SPRING_DATASOURCE_USERNAME=neondb_owner
      - SPRING_DATASOURCE_PASSWORD=npg_XQtTOLg98qpP
    depends_on:
      - postgres-db

  frontend:
    image: nginx:alpine
    volumes:
      - ./src/main/resources/static:/usr/share/nginx/html
    ports:
      - "80:80"

volumes:
  postgres-data:
